import type { CampaignArtifact, LevelSpec, PacingPhase } from '../types/levelgen';

const DEFAULT_HARD_RULES = {
  maxNewMechanicsPerChunk: 1,
  minRecoveryGap: 1,
  maxHazardClusters: 1,
};

type SpecChunkGroup = Array<{ phase: PacingPhase; chunks: string[] }>;

function level(
  world: number,
  level: number,
  title: string,
  sequence: SpecChunkGroup,
  hardRules: Partial<typeof DEFAULT_HARD_RULES> = {},
): LevelSpec {
  return {
    world,
    level,
    title,
    sequence,
    hardRules: { ...DEFAULT_HARD_RULES, ...hardRules },
  };
}

export const CAMPAIGN_25_LEVELS: CampaignArtifact = {
  version: '1.0.0',
  generatedAt: '2026-02-13T00:00:00.000Z',
  worldCount: 5,
  levels: [
    level(1, 1, 'Boot Camp I', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'flat_intro_02'] },
      { phase: 'PRACTICE', chunks: ['coin_stair_01', 'gap_short_guarded_01'] },
      { phase: 'VARIATION', chunks: ['flat_guide_01', 'platform_bubble_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'flat_step_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 1 }),
    level(1, 2, 'Boot Camp II', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'flat_guide_01'] },
      { phase: 'PRACTICE', chunks: ['gap_short_guarded_01', 'coin_arch_01'] },
      { phase: 'VARIATION', chunks: ['rise_step_01', 'platform_stack_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'walker_patrol_02'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'flat_guide_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 1 }),
    level(1, 3, 'Basic Coins I', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'coin_stair_01'] },
      { phase: 'PRACTICE', chunks: ['coin_rail_01', 'coin_arch_01'] },
      { phase: 'VARIATION', chunks: ['flat_guide_01', 'platform_bubble_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_02', 'coin_reward_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 1 }),
    level(1, 4, 'Safety Lanes', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'gap_short_guarded_01'] },
      { phase: 'PRACTICE', chunks: ['platform_bubble_01', 'platform_stack_01'] },
      { phase: 'VARIATION', chunks: ['rise_step_01', 'falloff_step_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'flat_guide_01', 'spike_low_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'platform_bubble_02'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 1 }),
    level(1, 5, 'Mini Boss Gate', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'flat_intro_02'] },
      { phase: 'PRACTICE', chunks: ['flat_guide_01', 'gap_short_guarded_01'] },
      { phase: 'VARIATION', chunks: ['platform_stack_01', 'coin_stair_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_02', 'shell_blocker_01', 'spike_low_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'coin_rail_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 1 }),
    level(1, 6, 'Run Onset', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'flat_guide_01'] },
      { phase: 'PRACTICE', chunks: ['coin_rail_01', 'rise_step_01'] },
      { phase: 'VARIATION', chunks: ['platform_bubble_01', 'platform_stack_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'walker_patrol_02', 'flying_drift_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'flat_guide_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 1 }),
    level(2, 1, 'Boot Camp II', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'rise_step_01'] },
      { phase: 'PRACTICE', chunks: ['gap_short_guarded_01', 'platform_stack_01'] },
      { phase: 'VARIATION', chunks: ['coin_arch_01', 'coin_reward_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'spike_sweep_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'platform_bubble_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 2 }),
    level(2, 2, 'Skid Timing', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'platform_bubble_01'] },
      { phase: 'PRACTICE', chunks: ['gap_short_guarded_01', 'gap_long_01'] },
      { phase: 'VARIATION', chunks: ['rise_step_01', 'platform_stack_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_02', 'walker_patrol_03'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'coin_rail_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { maxHazardClusters: 2 }),
    level(2, 3, 'Air Drift I', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'platform_bubble_01'] },
      { phase: 'PRACTICE', chunks: ['falloff_step_01', 'rise_step_01'] },
      { phase: 'VARIATION', chunks: ['coin_stair_01', 'gap_long_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'flying_drift_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_02', 'flat_guide_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { maxHazardClusters: 2 }),
    level(2, 4, 'Vertical Pressure', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'rise_step_01'] },
      { phase: 'PRACTICE', chunks: ['platform_stack_01', 'platform_bubble_01'] },
      { phase: 'VARIATION', chunks: ['falloff_step_01', 'gap_short_guarded_01'] },
      { phase: 'CHALLENGE', chunks: ['flying_drift_01', 'flat_guide_01', 'spike_low_01', 'recovery_lane_01', 'walker_patrol_02'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'platform_bubble_02'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { maxHazardClusters: 2 }),
    level(2, 5, 'Coin Bridges', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'coin_stair_01'] },
      { phase: 'PRACTICE', chunks: ['coin_arch_01', 'gap_short_guarded_01'] },
      { phase: 'VARIATION', chunks: ['coin_rail_01', 'rise_step_01'] },
      {
        phase: 'CHALLENGE',
        chunks: ['walker_patrol_03', 'flat_guide_01', 'spike_low_01', 'recovery_lane_01', 'walker_patrol_01'],
      },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'coin_reward_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { maxHazardClusters: 2 }),
    level(2, 6, 'Recovery Lab', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'flat_guide_01'] },
      { phase: 'PRACTICE', chunks: ['platform_bubble_01', 'platform_stack_01'] },
      { phase: 'VARIATION', chunks: ['rise_step_01', 'falloff_step_01'] },
      { phase: 'CHALLENGE', chunks: ['flying_drift_01', 'flying_drift_02'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { maxHazardClusters: 2 }),
    level(3, 1, 'Patrol Cadence', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'walker_patrol_01'] },
      { phase: 'PRACTICE', chunks: ['walker_patrol_02', 'walker_patrol_03'] },
      { phase: 'VARIATION', chunks: ['gap_short_guarded_01', 'coin_arch_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'shell_blocker_01', 'flat_guide_01', 'spike_low_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'platform_bubble_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { maxHazardClusters: 2 }),
    level(3, 2, 'Jump-Lock', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'flat_step_01'] },
      { phase: 'PRACTICE', chunks: ['gap_short_guarded_01', 'coin_stair_01'] },
      { phase: 'VARIATION', chunks: ['rise_step_01', 'falloff_step_01'] },
      { phase: 'CHALLENGE', chunks: ['flying_drift_01', 'walker_patrol_02', 'walker_patrol_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_02', 'platform_stack_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { maxHazardClusters: 2 }),
    level(3, 3, 'Telegraphed Hazards', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'recovery_lane_01'] },
      { phase: 'PRACTICE', chunks: ['spike_low_01', 'recovery_lane_01', 'spike_sweep_01'] },
      { phase: 'VARIATION', chunks: ['gap_short_guarded_01', 'coin_reward_01'] },
      { phase: 'CHALLENGE', chunks: ['spike_sweep_01', 'recovery_lane_01', 'walker_patrol_02', 'thwomp_intro_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'flat_guide_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { maxHazardClusters: 2 }),
    level(3, 4, 'Double Threat I', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'coin_arch_01'] },
      { phase: 'PRACTICE', chunks: ['walker_patrol_03', 'flying_drift_01'] },
      { phase: 'VARIATION', chunks: ['platform_bubble_01', 'gap_long_01'] },
      {
        phase: 'CHALLENGE',
        chunks: [
          'recovery_lane_01',
          'shell_blocker_01',
          'recovery_lane_01',
          'spike_low_01',
          'recovery_lane_01',
          'flat_guide_01',
          'flying_drift_02',
        ],
      },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { maxHazardClusters: 2 }),
    level(3, 5, 'Momentum Rhythm', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'rise_step_01'] },
      { phase: 'PRACTICE', chunks: ['platform_stack_01', 'platform_bubble_01'] },
      { phase: 'VARIATION', chunks: ['falloff_step_01', 'coin_stair_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'walker_patrol_03', 'shell_blocker_01', 'flat_guide_01', 'spike_low_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_02'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { maxHazardClusters: 2 }),
    level(3, 6, 'Final of World', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'flat_guide_01'] },
      { phase: 'PRACTICE', chunks: ['coin_arch_01', 'spike_sweep_01'] },
      { phase: 'VARIATION', chunks: ['gap_short_guarded_01', 'gap_long_01'] },
      {
        phase: 'CHALLENGE',
        chunks: ['flat_guide_01', 'thwomp_intro_01', 'recovery_lane_01', 'flying_drift_02', 'shell_blocker_01', 'walker_patrol_03'],
      },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01', 'platform_stack_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { maxHazardClusters: 2 }),
    level(4, 1, 'Thwomp Timing', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'thwomp_intro_01', 'recovery_lane_01'] },
      { phase: 'PRACTICE', chunks: ['flat_guide_01', 'spike_sweep_01', 'recovery_lane_01'] },
      { phase: 'VARIATION', chunks: ['gap_long_01', 'platform_bubble_01'] },
      { phase: 'CHALLENGE', chunks: ['flat_guide_01', 'thwomp_intro_01', 'recovery_lane_01', 'walker_patrol_02', 'walker_patrol_03'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_02'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 2 }),
    level(4, 2, 'Flicker Hazard Mix', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'falloff_step_01'] },
      { phase: 'PRACTICE', chunks: ['spike_low_01', 'spike_sweep_01'] },
      { phase: 'VARIATION', chunks: ['rise_step_01', 'gap_short_guarded_01'] },
      {
        phase: 'CHALLENGE',
        chunks: ['flat_guide_01', 'thwomp_intro_01', 'recovery_lane_01', 'flying_drift_01', 'flying_drift_02'],
      },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 2 }),
    level(4, 3, 'Enemy Traffic', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'flat_step_01'] },
      { phase: 'PRACTICE', chunks: ['walker_patrol_03', 'shell_blocker_01'] },
      { phase: 'VARIATION', chunks: ['platform_stack_01', 'platform_bubble_01'] },
      { phase: 'CHALLENGE', chunks: ['walker_patrol_01', 'walker_patrol_02', 'walker_patrol_03', 'shell_blocker_01'] },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_02', 'flat_guide_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 2 }),
    level(4, 4, 'Coin Rhythm II', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'coin_rail_01'] },
      { phase: 'PRACTICE', chunks: ['coin_stair_01', 'coin_arch_01'] },
      { phase: 'VARIATION', chunks: ['coin_reward_01', 'gap_long_01'] },
      {
        phase: 'CHALLENGE',
        chunks: [
          'flat_guide_01',
          'thwomp_intro_01',
          'recovery_lane_01',
          'walker_patrol_02',
          'flat_guide_01',
          'spike_sweep_01',
        ],
      },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 2 }),
    level(4, 5, 'Full Pace Form', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'rise_step_01'] },
      { phase: 'PRACTICE', chunks: ['platform_bubble_01', 'coin_stair_01'] },
      { phase: 'VARIATION', chunks: ['gap_short_guarded_01', 'falloff_step_01'] },
      {
        phase: 'CHALLENGE',
        chunks: [
          'flat_guide_01',
          'thwomp_intro_01',
          'recovery_lane_01',
          'walker_patrol_03',
          'shell_blocker_01',
          'flying_drift_02',
        ],
      },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_02', 'platform_stack_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 2 }),
    level(4, 6, 'Endurance Build', [
      { phase: 'INTRO', chunks: ['flat_intro_02', 'flat_guide_01'] },
      { phase: 'PRACTICE', chunks: ['gap_long_01', 'coin_rail_01'] },
      { phase: 'VARIATION', chunks: ['platform_stack_01', 'platform_bubble_01'] },
      {
        phase: 'CHALLENGE',
        chunks: ['flat_guide_01', 'walker_patrol_01', 'walker_patrol_02', 'flat_guide_01', 'spike_low_01', 'recovery_lane_01', 'flying_drift_01', 'shell_blocker_01'],
      },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_02', 'flat_guide_01'] },
      { phase: 'FINALE', chunks: ['flat_finish_01'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 2 }),
    level(5, 1, 'Finale Mastery', [
      { phase: 'INTRO', chunks: ['flat_intro_01', 'flat_guide_01'] },
      { phase: 'PRACTICE', chunks: ['gap_short_guarded_01', 'thwomp_intro_01'] },
      { phase: 'VARIATION', chunks: ['recovery_lane_01', 'rise_step_01', 'falloff_step_01', 'gap_long_01'] },
      {
        phase: 'CHALLENGE',
        chunks: [
          'flat_guide_01',
          'thwomp_intro_01',
          'recovery_lane_01',
          'walker_patrol_03',
          'flat_guide_01',
          'spike_sweep_01',
          'recovery_lane_01',
          'flying_drift_02',
          'shell_blocker_01',
          'benchmark_sprint_01',
        ],
      },
      { phase: 'COOLDOWN', chunks: ['recovery_lane_02', 'platform_bubble_02'] },
      { phase: 'FINALE', chunks: ['flat_finish_02'] },
    ], { minRecoveryGap: 2, maxHazardClusters: 3 }),
  ],
};
