import type { WorldLevelConstraint, WorldRuleset } from '../types/levelgen';
import { CONTENT_WORLD_MAP } from '../content/contentManifest';

const WORLD_CAMPAIGN_RULES: Record<number, WorldLevelConstraint> = {
  1: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'COIN_STAIR',
      'COIN_ARCH',
      'COIN_RAIL',
      'COIN_REWARD',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_LOW',
      'FLYER_DRIFT',
    ],
    allowedHazardTags: ['SPIKE_LOW'],
    allowedEnemyTags: ['walker', 'shell', 'flying', 'spike'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 1,
    maxHazardClusters: 1,
    guidanceWindow: 2,
    hazardWeights: {
      spike: 0.65,
      flying: 0.15,
      thwomp: 0.2,
    },
    enemyWeights: {
      walker: 0.82,
      shell: 0.18,
      flying: 0.0,
      thwomp: 0.0,
    },
    speedMultiplier: 1,
    gravityMultiplier: 1,
    tokenBurnRate: 1,
    tokenSpawnMultiplier: 1,
    hazardDensityMultiplier: 1,
  },
  2: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'COIN_STAIR',
      'COIN_ARCH',
      'COIN_RAIL',
      'COIN_REWARD',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_LOW',
      'SPIKE_SWEEP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
    ],
    allowedHazardTags: ['SPIKE_LOW', 'SPIKE_SWEEP'],
    allowedEnemyTags: ['walker', 'shell', 'flying', 'spike'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 1,
    maxHazardClusters: 2,
    guidanceWindow: 2,
    hazardWeights: {
      spike: 0.74,
      flying: 0.18,
      thwomp: 0.08,
    },
    enemyWeights: {
      walker: 0.8,
      shell: 0.1,
      flying: 0.1,
      thwomp: 0.0,
    },
    speedMultiplier: 1.08,
    gravityMultiplier: 1,
    tokenBurnRate: 1,
    tokenSpawnMultiplier: 0.78,
    hazardDensityMultiplier: 1.18,
  },
  3: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'COIN_STAIR',
      'COIN_ARCH',
      'COIN_REWARD',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_LOW',
      'SPIKE_SWEEP',
      'THWOMP_DROP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
    ],
    allowedHazardTags: ['SPIKE_LOW', 'SPIKE_SWEEP', 'THWOMP_DROP'],
    allowedEnemyTags: ['walker', 'shell', 'flying', 'spike', 'thwomp', 'spitter', 'technical_debt'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 1,
    maxHazardClusters: 2,
    guidanceWindow: 2,
    hazardWeights: {
      spike: 0.55,
      flying: 0.2,
      thwomp: 0.25,
    },
    enemyWeights: {
      walker: 0.65,
      shell: 0.15,
      flying: 0.2,
      thwomp: 0.0,
    },
    speedMultiplier: 1,
    gravityMultiplier: 1,
    tokenBurnRate: 1,
    tokenSpawnMultiplier: 0.95,
    hazardDensityMultiplier: 1,
  },
  4: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'COIN_STAIR',
      'COIN_ARCH',
      'COIN_RAIL',
      'COIN_REWARD',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_LOW',
      'SPIKE_SWEEP',
      'THWOMP_DROP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
      'VANISH_PLATFORM',
    ],
    allowedHazardTags: ['SPIKE_LOW', 'SPIKE_SWEEP', 'THWOMP_DROP'],
    allowedEnemyTags: ['walker', 'shell', 'flying', 'spike', 'thwomp', 'spitter', 'technical_debt', 'hot_take', 'compliance_officer', 'analyst'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 2,
    maxHazardClusters: 2,
    guidanceWindow: 2,
    hazardWeights: {
      spike: 0.46,
      flying: 0.36,
      thwomp: 0.18,
    },
    enemyWeights: {
      walker: 0.55,
      shell: 0.2,
      flying: 0.25,
      thwomp: 0.0,
    },
    speedMultiplier: 1.03,
    gravityMultiplier: 1.15,
    tokenBurnRate: 1.2,
    tokenSpawnMultiplier: 0.72,
    hazardDensityMultiplier: 1.22,
  },
  5: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_SWEEP',
      'THWOMP_DROP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
      'BENCHMARK_AUTO_SCROLL',
      'VANISH_PLATFORM',
    ],
    allowedHazardTags: ['SPIKE_SWEEP', 'THWOMP_DROP'],
    allowedEnemyTags: ['walker', 'shell', 'flying', 'spike', 'thwomp', 'spitter', 'technical_debt', 'hot_take', 'compliance_officer', 'analyst'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 2,
    maxHazardClusters: 3,
    guidanceWindow: 3,
    hazardWeights: {
      spike: 0.35,
      flying: 0.35,
      thwomp: 0.3,
    },
    enemyWeights: {
      walker: 0.45,
      shell: 0.25,
      flying: 0.25,
      thwomp: 0.05,
    },
    speedMultiplier: 1.08,
    gravityMultiplier: 1.25,
    tokenBurnRate: 1.3,
    tokenSpawnMultiplier: 0.64,
    hazardDensityMultiplier: 1.34,
  },
};

const WORLD_RULES: Record<number, WorldRuleset> = Object.fromEntries(
  CONTENT_WORLD_MAP.map((world) => [
    world.index,
    {
      theme: world.theme,
      multipliers: world.physicsMultipliers,
      groundVariance: world.generation.groundVariance,
      gapFrequency: world.generation.gapFrequency,
      enemyDensity: world.generation.enemyDensity,
      projectileCadenceMs: world.generation.projectileCadenceMs,
      movingPlatformFrequency: world.generation.movingPlatformFrequency,
      checkpointSpacingChunks: world.generation.checkpointSpacingChunks,
      coinDensity: world.generation.coinDensity,
      starTarget: world.generation.starTarget,
      palette: world.generation.palette,
      audio: world.generation.audio,
      allowedChunkFamilies: world.allowedChunkFamilies,
      campaign: WORLD_CAMPAIGN_RULES[world.index] ?? WORLD_CAMPAIGN_RULES[1],
      modifiers: {
        frictionMultiplier: world.physicsMultipliers.frictionMultiplier,
        gravityMultiplier: world.physicsMultipliers.gravityMultiplier,
        speedMultiplier: world.physicsMultipliers.speedMultiplier,
        tokenBurnRate: world.physicsMultipliers.tokenBurnRate
      }
    } as WorldRuleset,
  ]),
) as Record<number, WorldRuleset>;

export const WORLD_NAMES: Record<number, string> = Object.fromEntries(
  CONTENT_WORLD_MAP.map((world) => [world.index, world.displayName]),
);

export function getWorldRules(world: number): WorldRuleset {
  const maxWorld = CONTENT_WORLD_MAP.length;
  const safeWorld = Math.min(maxWorld, Math.max(1, world));
  return WORLD_RULES[safeWorld] ?? WORLD_RULES[1];
}
