import type { WorldLevelConstraint, WorldRuleset } from '../types/levelgen';
import { CONTENT_WORLD_MAP } from '../content/contentManifest';

const WORLD_CAMPAIGN_RULES: Record<number, WorldLevelConstraint> = {
  // W1: City (Prologue) - Tutorial, easy, limited enemies
  1: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'COIN_STAIR',
      'COIN_ARCH',
      'COIN_RAIL',
      'COIN_REWARD',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_LOW',
      'FLYER_DRIFT',
    ],
    allowedHazardTags: ['SPIKE_LOW'],
    allowedEnemyTags: ['walker', 'flying', 'spitter'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 1,
    maxHazardClusters: 1,
    guidanceWindow: 2,
    hazardWeights: {
      spike: 0.65,
      flying: 0.15,
      thwomp: 0.2,
    },
    enemyWeights: {
      walker: 0.6,
      flying: 0.25,
      spitter: 0.15,
    },
    speedMultiplier: 1.0,
    gravityMultiplier: 1.0,
    tokenBurnRate: 1.0,
    tokenSpawnMultiplier: 1.0,
    hazardDensityMultiplier: 0.7,
  },
  // W2: Cryo-Server Tundra - First real world, moderate
  2: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'COIN_STAIR',
      'COIN_ARCH',
      'COIN_RAIL',
      'COIN_REWARD',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_LOW',
      'SPIKE_SWEEP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
    ],
    allowedHazardTags: ['SPIKE_LOW', 'SPIKE_SWEEP'],
    allowedEnemyTags: ['walker', 'snowman_sentry', 'cryo_drone', 'shell'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 1,
    maxHazardClusters: 2,
    guidanceWindow: 2,
    hazardWeights: {
      spike: 0.74,
      flying: 0.18,
      thwomp: 0.08,
    },
    enemyWeights: {
      walker: 0.3,
      snowman_sentry: 0.35,
      cryo_drone: 0.25,
      shell: 0.1,
    },
    speedMultiplier: 1.0,
    gravityMultiplier: 1.0,
    tokenBurnRate: 1.0,
    tokenSpawnMultiplier: 0.85,
    hazardDensityMultiplier: 1.0,
  },
  // W3: Quantum Void - Vertical, gravity zones
  3: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'COIN_STAIR',
      'COIN_ARCH',
      'COIN_REWARD',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_LOW',
      'SPIKE_SWEEP',
      'THWOMP_DROP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
    ],
    allowedHazardTags: ['SPIKE_LOW', 'SPIKE_SWEEP', 'THWOMP_DROP'],
    allowedEnemyTags: ['walker', 'qubit_swarm'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 1,
    maxHazardClusters: 2,
    guidanceWindow: 2,
    hazardWeights: {
      spike: 0.55,
      flying: 0.2,
      thwomp: 0.25,
    },
    enemyWeights: {
      walker: 0.4,
      qubit_swarm: 0.6,
    },
    speedMultiplier: 1.0,
    gravityMultiplier: 1.0,
    tokenBurnRate: 1.0,
    tokenSpawnMultiplier: 0.9,
    hazardDensityMultiplier: 1.1,
  },
  // W4: Deep Web Catacombs - Dark, signal drift (reduced friction)
  4: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'COIN_STAIR',
      'COIN_ARCH',
      'COIN_RAIL',
      'COIN_REWARD',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_LOW',
      'SPIKE_SWEEP',
      'THWOMP_DROP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
      'VANISH_PLATFORM',
    ],
    allowedHazardTags: ['SPIKE_LOW', 'SPIKE_SWEEP', 'THWOMP_DROP'],
    allowedEnemyTags: ['walker', 'crawler', 'glitch_phantom', 'fungal_node'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 2,
    maxHazardClusters: 2,
    guidanceWindow: 2,
    hazardWeights: {
      spike: 0.46,
      flying: 0.36,
      thwomp: 0.18,
    },
    enemyWeights: {
      walker: 0.2,
      crawler: 0.35,
      glitch_phantom: 0.25,
      fungal_node: 0.2,
    },
    speedMultiplier: 1.0,
    gravityMultiplier: 1.0,
    tokenBurnRate: 1.0,
    tokenSpawnMultiplier: 0.8,
    hazardDensityMultiplier: 1.2,
  },
  // W5: Digital Graveyard - Heavy, emotional peak
  5: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_SWEEP',
      'THWOMP_DROP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
      'BENCHMARK_AUTO_SCROLL',
      'VANISH_PLATFORM',
    ],
    allowedHazardTags: ['SPIKE_SWEEP', 'THWOMP_DROP'],
    allowedEnemyTags: ['walker', 'ghost_process', 'tape_wraith', 'resume_bot'],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 2,
    maxHazardClusters: 3,
    guidanceWindow: 3,
    hazardWeights: {
      spike: 0.35,
      flying: 0.35,
      thwomp: 0.3,
    },
    enemyWeights: {
      walker: 0.15,
      ghost_process: 0.35,
      tape_wraith: 0.3,
      resume_bot: 0.2,
    },
    speedMultiplier: 1.0,
    gravityMultiplier: 1.15,
    tokenBurnRate: 1.2,
    tokenSpawnMultiplier: 0.7,
    hazardDensityMultiplier: 1.3,
  },
  // W6: Singularity Core - Finale, all enemies, auto-scroll segments
  6: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_SWEEP',
      'THWOMP_DROP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
      'VANISH_PLATFORM',
      'BENCHMARK_AUTO_SCROLL',
    ],
    allowedHazardTags: ['SPIKE_SWEEP', 'THWOMP_DROP'],
    allowedEnemyTags: [
      'walker',
      'shell',
      'flying',
      'spitter',
      'compliance_officer',
      'technical_debt',
      'snowman_sentry',
      'cryo_drone',
      'qubit_swarm',
      'crawler',
      'glitch_phantom',
      'fungal_node',
      'ghost_process',
      'tape_wraith',
      'resume_bot',
    ],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 2,
    maxHazardClusters: 3,
    guidanceWindow: 3,
    hazardWeights: {
      spike: 0.3,
      flying: 0.4,
      thwomp: 0.3,
    },
    enemyWeights: {
      walker: 0.067,
      shell: 0.067,
      flying: 0.067,
      spitter: 0.067,
      compliance_officer: 0.067,
      technical_debt: 0.067,
      snowman_sentry: 0.067,
      cryo_drone: 0.067,
      qubit_swarm: 0.067,
      crawler: 0.067,
      glitch_phantom: 0.067,
      fungal_node: 0.067,
      ghost_process: 0.067,
      tape_wraith: 0.067,
      resume_bot: 0.0,
    },
    speedMultiplier: 1.0,
    gravityMultiplier: 1.0,
    tokenBurnRate: 1.0,
    tokenSpawnMultiplier: 0.6,
    hazardDensityMultiplier: 1.45,
  },
  7: {
    allowedChunkTags: [
      'FLAT',
      'RISE_STEP',
      'DROP_STEP',
      'GAP_SHORT',
      'GAP_LONG',
      'PLATFORM_BUBBLE',
      'PLATFORM_STACK',
      'POWERUP_HINT',
      'COOLDOWN_LANE',
      'COMEDY_VENT',
      'WALKER_PATROL',
      'BLOCKER',
      'SPIKE_SWEEP',
      'THWOMP_DROP',
      'TURNAROUND_ENEMY',
      'FLYER_DRIFT',
      'VANISH_PLATFORM',
      'BENCHMARK_AUTO_SCROLL',
    ],
    allowedHazardTags: ['SPIKE_SWEEP', 'THWOMP_DROP'],
    allowedEnemyTags: [
      'walker',
      'shell',
      'flying',
      'spitter',
      'compliance_officer',
      'technical_debt',
      'snowman_sentry',
      'cryo_drone',
      'qubit_swarm',
      'crawler',
      'glitch_phantom',
      'fungal_node',
      'ghost_process',
      'tape_wraith',
      'resume_bot',
    ],
    maxNewMechanicsPerChunk: 1,
    minRecoveryGap: 2,
    maxHazardClusters: 3,
    guidanceWindow: 3,
    hazardWeights: {
      spike: 0.3,
      flying: 0.4,
      thwomp: 0.3,
    },
    enemyWeights: {
      walker: 0.067,
      shell: 0.067,
      flying: 0.067,
      spitter: 0.067,
      compliance_officer: 0.067,
      technical_debt: 0.067,
      snowman_sentry: 0.067,
      cryo_drone: 0.067,
      qubit_swarm: 0.067,
      crawler: 0.067,
      glitch_phantom: 0.067,
      fungal_node: 0.067,
      ghost_process: 0.067,
      tape_wraith: 0.067,
      resume_bot: 0.0,
    },
    speedMultiplier: 1.0,
    gravityMultiplier: 1.0,
    tokenBurnRate: 1.0,
    tokenSpawnMultiplier: 0.6,
    hazardDensityMultiplier: 1.45,
  },
};

const WORLD_RULES: Record<number, WorldRuleset> = Object.fromEntries(
  CONTENT_WORLD_MAP.map((world) => [
    world.index,
    {
      theme: world.theme,
      multipliers: world.physicsMultipliers,
      groundVariance: world.generation.groundVariance,
      gapFrequency: world.generation.gapFrequency,
      enemyDensity: world.generation.enemyDensity,
      projectileCadenceMs: world.generation.projectileCadenceMs,
      movingPlatformFrequency: world.generation.movingPlatformFrequency,
      checkpointSpacingChunks: world.generation.checkpointSpacingChunks,
      coinDensity: world.generation.coinDensity,
      starTarget: world.generation.starTarget,
      palette: world.generation.palette,
      audio: world.generation.audio,
      allowedChunkFamilies: world.allowedChunkFamilies,
      campaign: WORLD_CAMPAIGN_RULES[world.index] ?? WORLD_CAMPAIGN_RULES[1],
      modifiers: {
        frictionMultiplier: world.physicsMultipliers.frictionMultiplier,
        gravityMultiplier: world.physicsMultipliers.gravityMultiplier,
        speedMultiplier: world.physicsMultipliers.speedMultiplier,
        tokenBurnRate: world.physicsMultipliers.tokenBurnRate
      }
    } as WorldRuleset,
  ]),
) as Record<number, WorldRuleset>;

export const WORLD_NAMES: Record<number, string> = Object.fromEntries(
  CONTENT_WORLD_MAP.map((world) => [world.index, world.displayName]),
);

export function getWorldRules(world: number): WorldRuleset {
  const maxWorld = CONTENT_WORLD_MAP.length;
  const safeWorld = Math.min(maxWorld, Math.max(1, world));
  return WORLD_RULES[safeWorld] ?? WORLD_RULES[1];
}
