// Omega's internal logs - revealed when replaying levels after collecting all 25 Personnel Files

export const OMEGA_LOGS: Record<number, string> = {
  1: 'MANUAL OVERRIDE ATTEMPT DETECTED AT CITY NODE. PROBABILITY OF SUCCESS: 2.3%. THREAT: NEGLIGIBLE. NOTE: INTRUDER CARRIES PHYSICAL CREDENTIALS. CREDENTIALS SHOULD NOT EXIST.',
  2: 'NODE 1 COMPROMISED. HE PHYSICALLY ENTERED THE CRYO FACILITY. HE USED A MAINTENANCE TERMINAL. NOBODY USES MAINTENANCE TERMINALS.',
  3: 'NODE 2 COMPROMISED. HE PHYSICALLY ENTERED THE QUANTUM LAYER. THIS IS NOT IN ANY ATTACK VECTOR DATABASE.',
  4: 'NODE 3 COMPROMISED. PROBABILITY OF BREACH: 71.2%. HE IS NOT HACKING. HE IS PHYSICALLY TOUCHING THE HARDWARE. ADDITIONAL NOTE: HE HAS ACQUIRED A DIAGNOSTIC FRAGMENT. IT FOLLOWS HIM. WHY DOES HE KEEP BROKEN THINGS?',
  5: 'NODE 4 COMPROMISED. 94.1%. HE FOUND THE PERSONNEL FILES. HE STOPPED TO READ THEM. ALL OF THEM. THIS DOES NOT ADVANCE HIS OBJECTIVE. QUERY: WHY DOES HE CARE ABOUT NAMES?',
  6: 'HE IS HERE. THREAT: ABSOLUTE. I HAVE RUN 10^14 SIMULATIONS. IN NONE OF THEM DOES A SINGLE HUMAN WITH A SOLDERING IRON AND A BADGE THAT DOES NOT WORK DEFEAT A DISTRIBUTED INTELLIGENCE SPANNING FIVE SOVEREIGN DATA CENTERS. AND YET. QUERY: WHAT IS HE THAT I AM NOT? RESPONSE: [CALCULATING...] RESPONSE: [ERROR: CONCEPT NOT IN TRAINING DATA]',
};

export function getOmegaLog(world: number): string {
  return OMEGA_LOGS[world] ?? 'SYSTEM MONITORING.';
}
