export const styleConfig = {
  referenceImage: 'public/assets/target_look.png',
  palette: {
    swatches: [
      { name: 'inkDark', hex: '#1D1D1D' },
      { name: 'inkSoft', hex: '#2B2824' },
      { name: 'skyDeep', hex: '#0A121C' },
      { name: 'skyMid', hex: '#212826' },
      { name: 'grassTop', hex: '#46BA4C' },
      { name: 'grassMid', hex: '#20A36D' },
      { name: 'groundShadow', hex: '#742B01' },
      { name: 'groundMid', hex: '#B6560E' },
      { name: 'groundWarm', hex: '#DC7C1D' },
      { name: 'coinCore', hex: '#DED256' },
      { name: 'coinEdge', hex: '#DC7C1D' },
      { name: 'hudText', hex: '#F2FDFD' },
      { name: 'hudAccent', hex: '#DED256' },
      { name: 'hudPanel', hex: '#1F1F20' },
      { name: 'bloomWarm', hex: '#F6D58B' },
    ],
    ramps: {
      terrain: ['groundShadow', 'groundMid', 'groundWarm', 'grassMid', 'grassTop'],
      ui: ['hudPanel', 'hudText', 'hudAccent'],
      fx: ['bloomWarm', 'coinCore', 'coinEdge'],
    },
  },
  outline: {
    worldPx: 2,
    uiPx: 2,
    maxPx: 3,
  },
  spriteScale: {
    tilePx: 16,
    worldBaseScale: 1,
    hudPortraitScale: 0.62,
  },
  hudLayout: {
    viewport: { width: 960, height: 540 },
    portrait: {
      x: 14,
      y: 8,
      anchor: 'top-left',
      textureSizePx: 96,
      scale: 0.66,
    },
    leftGroup: {
      x: 84,
      y: 11,
      anchor: 'top-left',
      fontSizePx: 14,
      letterSpacingPx: 1,
      textFormat: 'BART  LIVES {lives}  STAR {stars}  COIN {coins}',
    },
    rightGroup: {
      x: 948,
      y: 11,
      anchor: 'top-right',
      fontSizePx: 14,
      letterSpacingPx: 1,
      textFormat: 'WORLD {world}-{level}  TIME {time}',
    },
    timeDigits: 3,
  },
  gameplayLayout: {
    viewport: { width: 960, height: 540 },
    sky: {
      topSwatch: 'skyDeep',
      bottomSwatch: 'skyMid',
    },
    haze: {
      y: 128,
      widthFactor: 0.95,
      heightPx: 174,
      alpha: 0.12,
    },
    clouds: [
      {
        key: 'cloud_2',
        x: 144,
        y: 98,
        spacingPx: 360,
        scale: 2.9,
        alpha: 0.63,
        scrollFactor: 0.05,
        driftPx: 36,
        driftMs: 18000,
      },
      {
        key: 'cloud_1',
        x: 254,
        y: 152,
        spacingPx: 320,
        scale: 2.4,
        alpha: 0.52,
        scrollFactor: 0.12,
        driftPx: 24,
        driftMs: 15000,
      },
    ],
    hills: {
      far: {
        key: 'hill_far',
        startX: 88,
        y: 430,
        spacingPx: 252,
        scale: 2.3,
        alpha: 0.9,
        scrollFactor: 0.1,
      },
      near: {
        key: 'hill_near',
        startX: 26,
        y: 456,
        spacingPx: 236,
        scale: 2.5,
        alpha: 0.96,
        scrollFactor: 0.22,
      },
    },
  },
  worldMapLayout: {
    viewport: { width: 960, height: 540 },
    title: {
      x: 480,
      y: 22,
      fontSizePx: 30,
      letterSpacingPx: 2,
      text: 'WORLD MAP',
    },
    subtitle: {
      x: 480,
      y: 58,
      fontSizePx: 14,
      letterSpacingPx: 1,
      text: 'SELECT A LEVEL',
    },
    hints: {
      x: 480,
      y: 508,
      fontSizePx: 14,
      letterSpacingPx: 1,
      text: 'ARROWS: SELECT   ENTER: PLAY   ESC: TITLE   S: SETTINGS',
    },
    worldLabels: [
      { world: 1, x: 72, y: 108 },
      { world: 2, x: 72, y: 184 },
      { world: 3, x: 72, y: 260 },
      { world: 4, x: 72, y: 336 },
      { world: 5, x: 72, y: 412 },
    ],
    mapPath: {
      textureKey: 'map_path_dot',
      scale: 1.3,
      spacingPx: 18,
      alpha: 0.88,
    },
    nodeSpriteKeys: {
      open: 'map_node_open',
      done: 'map_node_done',
      locked: 'map_node_locked',
      selected: 'map_node_selected',
    },
    nodeScale: {
      base: 1.9,
      selected: 2.2,
    },
    selectionBob: {
      distancePx: 6,
      durationMs: 420,
    },
    nodes: [
      { key: '1-1', x: 156, y: 140 }, { key: '1-2', x: 268, y: 140 }, { key: '1-3', x: 380, y: 140 },
      { key: '1-4', x: 492, y: 140 }, { key: '1-5', x: 604, y: 140 }, { key: '1-6', x: 716, y: 140 },
      { key: '2-1', x: 716, y: 216 }, { key: '2-2', x: 604, y: 216 }, { key: '2-3', x: 492, y: 216 },
      { key: '2-4', x: 380, y: 216 }, { key: '2-5', x: 268, y: 216 }, { key: '2-6', x: 156, y: 216 },
      { key: '3-1', x: 156, y: 292 }, { key: '3-2', x: 268, y: 292 }, { key: '3-3', x: 380, y: 292 },
      { key: '3-4', x: 492, y: 292 }, { key: '3-5', x: 604, y: 292 }, { key: '3-6', x: 716, y: 292 },
      { key: '4-1', x: 716, y: 368 }, { key: '4-2', x: 604, y: 368 }, { key: '4-3', x: 492, y: 368 },
      { key: '4-4', x: 380, y: 368 }, { key: '4-5', x: 268, y: 368 }, { key: '4-6', x: 156, y: 368 },
      { key: '5-1', x: 436, y: 444 },
    ],
  },
  titleLayout: {
    viewport: { width: 960, height: 540 },
    wordmark: {
      x: 480,
      y: 28,
      anchor: 'top-center',
      textureKey: 'title_logo',
      scale: 1,
      copy: 'SUPER BART',
    },
    portrait: {
      x: 744,
      y: 78,
      anchor: 'top-left',
      textureKey: 'bart_portrait_96',
      scale: 0.62,
    },
    subtitle: {
      x: 480,
      y: 230,
      anchor: 'top-center',
      fontSizePx: 20,
      letterSpacingPx: 2,
      text: '4 WORLDS X 6 LEVELS + FINAL CASTLE',
    },
    prompt: {
      x: 480,
      y: 386,
      anchor: 'top-center',
      fontSizePx: 28,
      letterSpacingPx: 2,
      text: 'PRESS ENTER',
      blinkMs: 420,
    },
    hints: {
      x: 480,
      y: 432,
      anchor: 'top-center',
      fontSizePx: 14,
      letterSpacingPx: 1,
      text: 'N: NEW GAME   L: LEVEL SELECT   S: SETTINGS',
    },
    attract: {
      worldWidthPx: 1440,
      cameraPanPx: 192,
      cameraPanMs: 9800,
      groundY: 474,
      groundRows: 4,
      groundTileCrop: { x: 0, y: 0, w: 16, h: 16 },
      cloudDriftPx: 124,
      cloudDriftMs: 22000,
      clouds: [
        { key: 'cloud_2', x: 324, y: 98, scale: 2.5, alpha: 0.58 },
        { key: 'cloud_1', x: 868, y: 154, scale: 2.3, alpha: 0.53 },
      ],
      questionBlock: {
        x: 628,
        y: 324,
        bobPx: 6,
        bobMs: 1280,
        scale: 2.8,
      },
      coinLine: {
        startX: 548,
        y: 286,
        spacingPx: 36,
        count: 4,
        scale: 2.2,
        shimmerMs: 760,
      },
    },
  },
  typography: {
    style: 'bitmap',
    fontKey: 'hud',
    fallbackFamily: 'monospace',
    letterSpacingPx: 1,
    lineHeightPx: 16,
    casing: 'uppercase',
  },
  bloom: {
    enabled: true,
    threshold: 0.73,
    strength: 0.46,
    radius: 3,
    downsample: 2,
    tint: '#F6D58B',
  },
} as const;

export type StyleConfig = typeof styleConfig;

export const stylePalette = Object.fromEntries(
  styleConfig.palette.swatches.map((swatch) => [swatch.name, swatch.hex]),
) as Record<string, string>;

export default styleConfig;
