// Auto-generated by tools/make_body_spritesheet.ts — do not edit manually

export interface HeadOffset {
  dx: number;
  dy: number;
}

export const SMALL_HEAD_OFFSETS: readonly HeadOffset[] = [
  { dx: 0, dy: -12 },
  { dx: 0, dy: -12 },
  { dx: 0, dy: -11 },
  { dx: 0, dy: -12 },
  { dx: 1, dy: -12 },
  { dx: 1, dy: -11 },
  { dx: 1, dy: -12 },
  { dx: -1, dy: -12 },
  { dx: 0, dy: -13 },
  { dx: 0, dy: -12 },
  { dx: 0, dy: -8 },
  { dx: -1, dy: -11 },
  { dx: 0, dy: -14 },
  { dx: 0, dy: -8 },
] as const;

export const BIG_HEAD_OFFSETS: readonly HeadOffset[] = [
  { dx: 0, dy: -14 },
  { dx: 0, dy: -14 },
  { dx: 0, dy: -13 },
  { dx: 0, dy: -14 },
  { dx: 1, dy: -14 },
  { dx: 1, dy: -13 },
  { dx: 1, dy: -14 },
  { dx: -1, dy: -14 },
  { dx: 0, dy: -15 },
  { dx: 0, dy: -14 },
  { dx: 0, dy: -8 },
  { dx: -1, dy: -13 },
  { dx: 0, dy: -16 },
  { dx: 0, dy: -8 },
] as const;
